apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dsadsa-node 
  janus-idp.io/tekton: dsadsa-node
  backstage.io/kubernetes-id: dsadsa-node
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dsadsa-node
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  