apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dsadsa-node-gitops
  description: This is GitOps manifest for dsadsa-node   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dsadsa-node
    janus-idp.io/tekton: dsadsa-node 
    backstage.io/kubernetes-id: dsadsa-node 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dsadsa-node
