apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dsadsa-node
  janus-idp.io/tekton: dsadsa-node
  backstage.io/kubernetes-id: dsadsa-node
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dsadsa-node
resources: 
- deployment.yaml
- route.yaml
- service.yaml
